import { describe, it, expect } from "@jest/globals";
import { helloWorld } from "./hello-world";

/**
 * Test suite for hello world function
 * Generated by FlowX Swarm Coordination - Tester Agent
 * 
 * Test cases cover:
 * - Default behavior
 * - Personalized greetings
 * - Edge cases (empty strings, special characters)
 * - Type safety validation
 */

describe("helloWorld", () => {
  it("should return default greeting", () => {
    expect(helloWorld()).toBe("Hello, World!");
  });

  it("should return personalized greeting", () => {
    expect(helloWorld("Alice")).toBe("Hello, Alice!");
  });

  it("should handle empty string", () => {
    expect(helloWorld("")).toBe("Hello, !");
  });

  it("should handle special characters", () => {
    expect(helloWorld("José")).toBe("Hello, José!");
    expect(helloWorld("123")).toBe("Hello, 123!");
  });

  it("should handle long names", () => {
    const longName = "A".repeat(100);
    expect(helloWorld(longName)).toBe(`Hello, ${longName}!`);
  });

  it("should handle whitespace names", () => {
    expect(helloWorld(" ")).toBe("Hello,  !");
    expect(helloWorld("\t")).toBe("Hello, \t!");
  });
}); 