/**
 * Simple hello world function
 * Generated by FlowX Swarm Coordination
 * 
 * This function demonstrates collaborative development between:
 * - Architect Agent: Designed the function signature and interface
 * - Developer Agent: Implemented the core functionality
 * - Tester Agent: Specified test cases and edge cases
 */

export function helloWorld(name: string = "World"): string {
  return `Hello, ${name}!`;
}

export default helloWorld; 